config/routes.rb
Rails.application.routes.draw do
  resources :money_movements
  resources :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/money_movement.rb
class MoneyMovement < ApplicationRecord
  belongs_to :from_account, class_name: "Account"
  belongs_to :to_account, class_name: "Account"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/money_movements_controller.rb
class MoneyMovementsController < ApplicationController
  before_action :set_money_movement, only: [:show, :edit, :update, :destroy]

  # GET /money_movements
  # GET /money_movements.json
  def index
    @money_movements = MoneyMovement.all
  end

  # GET /money_movements/1
  # GET /money_movements/1.json
  def show
  end

  # GET /money_movements/new
  def new
    @money_movement = MoneyMovement.new
  end

  # GET /money_movements/1/edit
  def edit
  end

  # POST /money_movements
  # POST /money_movements.json
  def create
    @money_movement = MoneyMovement.new(money_movement_params)

    respond_to do |format|
      if @money_movement.save
        format.html { redirect_to @money_movement, notice: 'Money movement was successfully created.' }
        format.json { render :show, status: :created, location: @money_movement }
      else
        format.html { render :new }
        format.json { render json: @money_movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money_movements/1
  # PATCH/PUT /money_movements/1.json
  def update
    respond_to do |format|
      if @money_movement.update(money_movement_params)
        format.html { redirect_to @money_movement, notice: 'Money movement was successfully updated.' }
        format.json { render :show, status: :ok, location: @money_movement }
      else
        format.html { render :edit }
        format.json { render json: @money_movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money_movements/1
  # DELETE /money_movements/1.json
  def destroy
    @money_movement.destroy
    respond_to do |format|
      format.html { redirect_to money_movements_url, notice: 'Money movement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money_movement
      @money_movement = MoneyMovement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def money_movement_params
      params.require(:money_movement).permit(:amount, :from_account_id, :to_account_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/money_movements_helper.rb
module MoneyMovementsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultipleAssociationSameTable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/money_movements/_form.html.erb
<%= form_with(model: money_movement, local: true) do |form| %>
  <% if money_movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(money_movement.errors.count, "error") %> prohibited this money_movement from being saved:</h2>

      <ul>
        <% money_movement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :from_account_id %>
    <%= form.collection_select :from_account_id, Account.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :to_account_id %>
    <%= form.collection_select :to_account_id, Account.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/money_movements/edit.html.erb
<h1>Editing Money Movement</h1>

<%= render 'form', money_movement: @money_movement %>

<%= link_to 'Show', @money_movement %> |
<%= link_to 'Back', money_movements_path %>

app/views/money_movements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Money Movements</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>From account</th>
      <th>To account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @money_movements.each do |money_movement| %>
      <tr>
        <td><%= number_with_precision money_movement.amount, :precision => 2 %></td>
        <td><%= money_movement.from_account.name %></td>
        <td><%= money_movement.to_account.name %></td>
        <td><%= link_to 'Show', money_movement %></td>
        <td><%= link_to 'Edit', edit_money_movement_path(money_movement) %></td>
        <td><%= link_to 'Destroy', money_movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Total: <%= number_with_precision @money_movements.sum(:amount), :precision => 2 %>

<br>

<%= link_to 'New Money Movement', new_money_movement_path %>

app/views/money_movements/new.html.erb
<h1>New Money Movement</h1>

<%= render 'form', money_movement: @money_movement %>

<%= link_to 'Back', money_movements_path %>

app/views/money_movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @money_movement.amount %>
</p>

<p>
  <strong>From account:</strong>
  <%= @money_movement.from_account.name %>
</p>

<p>
  <strong>To account:</strong>
  <%= @money_movement.to_account.name %>
</p>

<%= link_to 'Edit', edit_money_movement_path(@money_movement) %> |
<%= link_to 'Back', money_movements_path %>